# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build_HybridFramework
on: workflow_dispatch
  #push:
    #branches: [ "master" ]
 # pull_request:
    #branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test verify --file pom.xml  

    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Specify connection via URL (replaces server_address, server_port, secure,
        # username and password)
        #
        # Format:
        #
        #  * smtp://user:password@server:port
        #  * smtp+starttls://user:password@server:port
        #connection_url: ${{secrets.MAIL_CONNECTION}}
        # Required mail server address if not connection_url:
        server_address: smtp.gmail.com
        # Server port, default 25:
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: jenkinsbuild.mails@gmail.com
        # Optional (recommended) mail server password:
        password: kojc yftf kjfi cyvb
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: manju.m005@gmail.com
        # Required sender full name (address can be skipped):
        from: jenkinsbuild.mails@gmail.com # <user@example.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        html_body: '<h1>Test-Report</h1> <h3> Hi Team, <br> please find attached report</br><h3>'
        # Optional carbon copy recipients:
        #cc: kyloren@example.com,leia@example.com
        # Optional blind carbon copy recipients:
       # bcc: r2d2@example.com,hansolo@example.com
        # Optional recipient of the email response:
        reply_to: jenkinsbuild.mails@gmail.com
        # Optional Message ID this message is replying to:
        #in_reply_to: <random-luke@example.com>
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: ./Reports/ExtentReport*/HTML_Report/*.html
        #attachments.zip,git.diff,./dist/static/*.js        
